select * from
[INC 5000].dbo.Sheet2$;

-- Sum the revenue generated from each industry
SELECT 
	industry,
	sum([Revenue ($M)]) as "Industry_Revenue"
FROM [INC 5000].dbo.Sheet2$
GROUP BY Industry
ORDER BY "Industry_Revenue" DESC;


-- Identify all the companies under Financial Services

SELECT 
	company,
	industry,
	[Revenue ($M)]
FROM [INC 5000].dbo.Sheet2$
WHERE industry  IN ('Financial Services')
ORDER BY [Revenue ($M)] ASC;


-- Identify the company with the highest revenue from the Financial Services Industry

SELECT TOP 1
	company,
	[Revenue ($M)]
FROM [INC 5000].dbo.Sheet2$
WHERE industry IN ('Financial Services')
ORDER BY [Revenue ($M)] DESC 

-- Calculate the percentage of the revenue made by Freedom Mortgage against the total revenue generated from the Financial Services industry
SELECT 
	Company,
	ROUND([Revenue ($M)] *100/ (SELECT sum([Revenue ($M)])
			  FROM [INC 5000].dbo.Sheet2$
			  WHERE industry IN ('Financial Services')),2) As Percentage
FROM [INC 5000].dbo.Sheet2$
WHERE "company" IN ('Freedom Mortgage');


-- Calculate the percentage of revenue generated by each industry from the total revenue generated
SELECT 
	industry, 
	ROUND(sum([Revenue ($M)])*100/(SELECT sum([Revenue ($M)])
				FROM [INC 5000].dbo.Sheet2$),2) As Percentage
FROM [INC 5000].dbo.Sheet2$
GROUP BY industry
ORDER BY Percentage DESC;


-- Identifying trends from state
SELECT
	"state",
	sum([Revenue ($M)]) as "Industry_Revenue"
FROM [INC 5000].dbo.Sheet2$
GROUP BY "state"
ORDER BY "Industry_Revenue" DESC;

-- Number of companies in each state
SELECT
	"state",
	count("company") as "companies"
FROM [INC 5000].dbo.Sheet2$
GROUP BY "state"
ORDER BY "companies" DESC;


-- Industry with the average highest growth rate
SELECT TOP 3
	industry,
	ROUND(avg("growth"),2) AS "Growth Rate"
FROM [INC 5000].dbo.Sheet2$
GROUP BY industry
ORDER BY "Growth Rate" DESC;


-- Identify the number of years the company with the highest revenue have been listed
SELECT top 3
	Company,
	industry,
	[Revenue ($M)],
	[Years on the List]
FROM [INC 5000].dbo.Sheet2$
ORDER BY [Revenue ($M)] DESC 

-- Identify companies and industries with the lowest revenue, limit to 3
SELECT TOP 3
	company,
	industry,
	[Revenue ($M)]
FROM [INC 5000].dbo.Sheet2$
ORDER BY [Revenue ($M)] ASC

-- Identify the companies and industries with the highest growth rate
SELECT TOP 5
	company,
	industry,
	[Revenue ($M)],
	Growth
FROM [INC 5000].dbo.Sheet2$
ORDER BY Growth DESC

-- Identify the companies and industries with the lowest growth rate
SELECT TOP 5
	company,
	industry,
	[Revenue ($M)],
	Growth
FROM [INC 5000].dbo.Sheet2$
ORDER BY Growth ASC





